apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: acme

commonLabels:
  tenant: acme
    
namePrefix: acme-

configMapGenerator:
- name: wpdb-cm 
  behavior: merge
  literals:
  - MYSQL_DATABASE=acmedb
  - MYSQL_USER=fred

secretGenerator:
- name: wpdb-secret 
  behavior: merge
  literals:
  - MYSQL_ROOT_PASSWORD=changeit
  - MYSQL_PASSWORD=fredfred

replacements:
- source:
    kind: Service
    name: wpdb-svc
    fieldPath: metadata.name
  targets:
  - select:
      kind: StatefulSet
      name: wp-sts
    fieldPaths:
    - spec.template.spec.containers.[name=wp].env.[name=WORDPRESS_DB_HOST].value

patches:
- path: ./fqdn.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: wp-ing
